---
starttime: 1
interval: 1
updates: true
send_to: 
- 
jobs:
- vendor: Fortinet
  products:
  - fortios
  - fortigate
  - fortianalyzer
  - fortimanager
  - fortiauthenticator
  - forticlient
  - fortinet enterprise management server  
  - fortinet ems  
  - forticlient ems  
  additional_parameters: {}
...